apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - mongodb/secret.yaml
  - mongodb/pvc.yaml
  - mongodb/service.yaml
  - mongodb/statefulset.yaml

  - backend/configmap.yaml
  - backend/backend-secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - ingress/ingress.yaml

  - hpa/back-end-hpa.yaml
  - hpa/front-end-hpa.yaml

  - RBAC/serviceaccount.yaml
  - RBAC/role.yaml
  - RBAC/rolebinding.yaml

  - network-policy.yaml