apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: mern

type: Opaque

stringData:
  MONGO_URI: mongodb://mongoadmin:MernMongo123@mongodb-service:27017/mern_ecommerce?authSource=admin
  JWT_SECRET: MernJWT@123