name: MERN CD Pipeline

on:

  workflow_run:
    workflows: ["MERN CI Pipeline"]
    types:
      - completed

jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    permissions:
      contents: write

    steps:

      ####################################################
      # Checkout GitOps Repository
      ####################################################

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: Lohitht909/Application-GitOps
          token: ${{ secrets.GH_TOKEN }}

      ####################################################
      # Update Backend Image
      ####################################################

      - name: Update Backend Image
        run: |

          sed -i "s|image:.*mern-backend:.*|image: 483176634994.dkr.ecr.us-east-1.amazonaws.com/mern-backend:${{ github.event.workflow_run.run_number }}|g" backend/deployment.yaml

      ####################################################
      # Update Frontend Image
      ####################################################

      - name: Update Frontend Image
        run: |

          sed -i "s|image:.*mern-frontend:.*|image: 483176634994.dkr.ecr.us-east-1.amazonaws.com/mern-frontend:${{ github.event.workflow_run.run_number }}|g" frontend/deployment.yaml

      ####################################################
      # Commit
      ####################################################

      - name: Commit Changes
        run: |

          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

          git add .

          git commit -m "Updated image to build ${{ github.event.workflow_run.run_number }}" || exit 0

      ####################################################
      # Push
      ####################################################

      - name: Push Changes
        run: |

          git push
